"""Update

Revision ID: e487cae99ce5
Revises: 
Create Date: 2024-11-23 09:25:59.354805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e487cae99ce5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Agronomist', schema=None) as batch_op:
        batch_op.alter_column('agronomist_name',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)

    with op.batch_alter_table('Field', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Field', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('Agronomist', schema=None) as batch_op:
        batch_op.alter_column('agronomist_name',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)

    # ### end Alembic commands ###
